In [1]:
import numpy as np
from optimizer.newtonMethod import NewtonMethod, GillMurrayNewton, FletcherFreemanMethod
from optimizer.steepestDescent import SteepestDescent
from linearSearch.monotoneSearch import AccurateLinearSearch, InaccurateLinearSearch
from linearSearch.nonmonotoneSearch import NonmonotoneGLL
from testFunction import ExtendedPowellSingular, Rosenbrock, BiggsEXP6, PowellBadlyScaled

BEXP_m = 13
EPS_m, EPS_n = 80, 80
PBS, RF, EPS, BEXP = PowellBadlyScaled(), Rosenbrock(), ExtendedPowellSingular(m=EPS_m, n=EPS_n), BiggsEXP6(
    m=BEXP_m)
PBS_x0, RF_x0, EPS_x0, BEXP_x0 = np.array([0, 1]).reshape((2, 1)), \
                                 np.array([-1.2, 1]).reshape((2, 1)), \
                                 np.array([3, -1, 0, 1] * (EPS_m // 4)).reshape((EPS_m, 1)), \
                                 np.array([1, 2, 1, 1, 1, 1]).reshape(6, 1)
PBS_xx, RF_xx, EPS_xx, BEXP_xx = np.array([1.098e-5, 9.106]).reshape((2, 1)), \
                                 np.array([1, 1]).reshape((2, 1)), \
                                 np.array([0] * EPS_m).reshape((EPS_m, 1)), \
                                 np.array([1, 10, 1, 5, 4, 3]).reshape((-1, 1))

In [2]:
from optimizer.trustRegionMethod import TrustRegion

In [25]:
method = TrustRegion(subq_method="subspace", delta=0.01, max_iter=1000)

In [26]:
x = method.compute(PBS.f, PBS.g, PBS.gg, PBS_x0)

[[0.00010068]
 [0.00996748]]
[[-4.70367678e-06]
 [ 3.00000021e-02]]
[[-8.10691349e-06]
 [ 9.00000015e-02]]
[[-2.02153351e-05]
 [ 2.70000000e-01]]
[[-3.31826518e-05]
 [ 8.09999998e-01]]
[[2.09385255e-06]
 [8.09999999e-01]]
[[-6.59004426e-06]
 [ 4.49161624e-01]]
[[-4.29671882e-06]
 [ 4.54913850e-01]]
[[-9.65155673e-06]
 [ 1.44621339e+00]]
[[-3.58978914e-06]
 [ 5.19203037e-01]]
[[-1.14731139e-06]
 [ 1.45681270e-01]]
[[-2.70149903e-06]
 [ 4.55625000e-01]]
[[-1.90298499e-06]
 [ 4.55625000e-01]]
[[-2.74798781e-07]
 [ 1.13906250e-01]]
[[-1.58752248e-06]
 [ 3.41718750e-01]]
[[-1.25349574e-06]
 [ 3.41718750e-01]]
[[-3.51670155e-06]
 [ 1.02515625e+00]]
[[-6.53746054e-06]
 [ 3.07546875e+00]]
[[-4.61540238e-06]
 [ 9.22640625e+00]]
[[9.80314840e-07]
 [2.30660156e+00]]
[[-2.58327328e-07]
 [ 8.95750858e-01]]
[[-1.93510834e-07]
 [ 7.60917853e-01]]
[[-1.52884778e-07]
 [ 6.62806005e-01]]
[[-1.25282724e-07]
 [ 5.87926409e-01]]
[[-1.05440191e-07]
 [ 5.28760590e-01]]
[[-9.05658435e-08]
 [ 4.80755038e-01]]
